// <auto-generated />
using System;
using FishMarket.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FishMarket.Migrations
{
    [DbContext(typeof(FishMarketContext))]
    partial class FishMarketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FishMarket.Models.FishStockModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("LatestPrice");

                    b.Property<double>("Quantity");

                    b.Property<int>("SpecieId");

                    b.HasKey("Id");

                    b.HasIndex("SpecieId");

                    b.ToTable("FishStocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LatestPrice = 10.0,
                            Quantity = 10000.0,
                            SpecieId = 1
                        },
                        new
                        {
                            Id = 2,
                            LatestPrice = 25.0,
                            Quantity = 20000.0,
                            SpecieId = 2
                        },
                        new
                        {
                            Id = 3,
                            LatestPrice = 75.0,
                            Quantity = 10000.0,
                            SpecieId = 3
                        });
                });

            modelBuilder.Entity("FishMarket.Models.SpecieModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageSrc");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageSrc = "https://media.istockphoto.com/photos/three-fresh-seabass-fish-on-plate-picture-id466288735",
                            Name = "Seabass"
                        },
                        new
                        {
                            Id = 2,
                            ImageSrc = "https://media.istockphoto.com/photos/three-fresh-seabass-fish-on-plate-picture-id466288735",
                            Name = "Perch"
                        },
                        new
                        {
                            Id = 3,
                            ImageSrc = "https://5.imimg.com/data5/YA/LX/MY-8948116/tuna-fish-500x500.jpg",
                            Name = "Tuna"
                        });
                });

            modelBuilder.Entity("FishMarket.Models.FishStockModel", b =>
                {
                    b.HasOne("FishMarket.Models.SpecieModel", "Specie")
                        .WithMany()
                        .HasForeignKey("SpecieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
